[package]
name = "rustc-noodling"
version = "0.0.1"
authors = ["Phil Dawes <phil@phildawes.net"]

[[bin]]
name = "try2"
path = "src/try2.rs"

[dependencies]
time = "*"

[profile.release]
debug = true

[dependencies.mytypeck]
path="mytypeck"
